### ISSUE TITLE
Coalton thinks (-> (Liszt t) t) is a binary function

### ISSUE THREAD

**Issue by stylewarning** [tarballs-are-good/coalton#2]
This is a usability issue, not a technical one. The proper way to write the type as of writing is `(-> ((Liszt t)) t)`, but it will certainly trip people up.

**Comment by fiddlerwoaroof** [comment]
I wonder if a ML-style `(-> ((a Liszt)) a)` might be a better choice for type expressions rather than the Haskell-like `(-> ((Liszt a)) a)`.  Generic function specializers already have the variable before its associated type, although the type there isn't exactly the same sort of thing as this use-case.

**Comment by stylewarning** [comment]
@fiddlerwoaroof Perhaps, but I do like the fact that `Liszt` can be seen as a function on types.

**Comment by stylewarning** [comment]
Some random thoughts:

```
((Liszt a) -> a)
(fn (Liszt a) -> a)
```

**Comment by stylewarning** [comment]
fixed since syntax changed to `(fn (liszt a) -> a)`
